# Generated by Django 3.2.3 on 2021-09-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20210917_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='no image', upload_to='recipe/', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
