version: '3.8'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:12.4
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    image: 6turm/foodgram:latest
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static_volume:/code/static/
      - media_volume:/code/media/
    ports:
          - "8000:8000"

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - web
