version: '3.8'

volumes:
  postgres_data:
  static_valume:
  media_valume:

services:
  db:
    image: postgres:12.4
    restart: always
    container_name: postgres
    env_file:
      - ./.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

  web:
    image: 6turm/foodgram:latest
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_valume:/code/static/
      - media_valume:/code/media/
    depends_on:
      - web
